language: node_js
env:
  global:
    - GH_REF: github.com/w3c/personalization-semantics.git
    - secure: "TlIXLRNEa2LZA7J63Q2uBoEkVAWoaZ9HAnzuI06nJoSfunkRwA1/iPT2h/xBDCnh8SPaRKWulGy328qz3Wn9TXvswCvLSytI1WYisEjAUk4W9xGD80Jebq5QkLNFC94s5lXu85ALyEIZ0ddPev/LNpRTY1P+1B1Z58c5mRy2nCdvFcIRU3O1vRNmq+OoL2SWG1c14uIF+sYpSicfnjRW3Xt8+r+NVDuMFlds+hQj8UAaJdcLIxpGH7ewoetHHZsYw+f6pA0kUNwzefHYUadB+kAs1ZeI5mKx+NWXKKiZTrcCtKjhZBYMSp0BSB2M2cQtkV+4C8rM637s5h8nEpmJjNH8l1aHN7TSWeVnIoBPy9bkPP5NMxowmBoaXbPxLSD/dGBxC1KY0KmyYoanQ+cdgRGm77Hnej0zh7jTWdZjWxE0pdHjQfHLJk9zgmrq0EDzMa6LYGYHEShxeiwEP2p7BsSw7MArhliZag1eAAsiDmjbPzp8wCXYcHnEYXDLPyZPrdyFCIVjm3nyJ6oJKNvJDVrbkTQeokWaLQw69HWH9j/uKuzTkmDD4l3H9fIDjv+1BJZ/lOCBIocriOc/FSsgW+Y2w8tl8+zabQjyxURUzGpe32H0rDFt/H22Xxc18THo4edy9LfiTmAsOiiCCrjeA1ALvvFdeb41HuDZqUetWyk="
    
git:
  depth: 3
  
branches:
  only:
    master

before_script:
  - git config --global user.email "cooper@w3.org"
  - git config --global user.name "michael-n-cooper"
  
script:
  - cd ../..
  - mkdir gh-pages
  - cd gh-pages
  - git clone --depth=1 --branch=gh-pages https://github.com/w3c/personalization-semantics.git
  - cd personalization-semantics
  - curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://rawgit.com/w3c/personalization-semantics/master/semantics.html -o index.html -f

after_success:
  - git add -A .
  - git commit -m "Generated by TRAVIS-CI"
  - git push "https://${GH_TOKEN}@${GH_REF}" gh-pages
